set serveroutput on
DECLARE
   TYPE IM_GROUP_MESSAGE_TAB IS TABLE OF IM_GROUP_MESSAGE%ROWTYPE;

   IM_GROUP_MESSAGE_HIST   IM_GROUP_MESSAGE_TAB := IM_GROUP_MESSAGE_TAB ();
   START_TIME     NUMBER;
   END_TIME       NUMBER;
   IM_GROUP_MESSAGE_HIST_CNT      NUMBER;
   IM_GROUP_MESSAGE_CNT NUMBER;
   ARCH_DATE                varchar2(40);
   
BEGIN
   SELECT TO_CHAR(SYSDATE-30,'YYYY-MM-DD') INTO ARCH_DATE  FROM DUAL;
   START_TIME := DBMS_UTILITY.GET_TIME;

   SELECT COUNT(*) INTO IM_GROUP_MESSAGE_CNT
     FROM IM_GROUP_MESSAGE
    WHERE CREATE_DATE >= TRUNC(SYSDATE-30) AND CREATE_DATE < TRUNC(SYSDATE-29) ;

   SELECT COUNT(*) INTO IM_GROUP_MESSAGE_HIST_CNT
     FROM IM_GROUP_MESSAGE_HIST
    WHERE CREATE_DATE >= TRUNC(SYSDATE-30) AND CREATE_DATE < TRUNC(SYSDATE-29) ;
	
   IF IM_GROUP_MESSAGE_HIST_CNT = 0
   THEN
      -- POPULATE A COLLECTION - 100000 ROWS
      SELECT *
        BULK COLLECT INTO IM_GROUP_MESSAGE_HIST
        FROM IM_GROUP_MESSAGE
	    WHERE  CREATE_DATE  >= TRUNC(SYSDATE-30) AND CREATE_DATE < TRUNC(SYSDATE-29);
	 
      FORALL I IN IM_GROUP_MESSAGE_HIST.FIRST .. IM_GROUP_MESSAGE_HIST.LAST
         INSERT INTO IM_GROUP_MESSAGE_HIST
              VALUES IM_GROUP_MESSAGE_HIST (I); 

      COMMIT;
	  
      SELECT COUNT(*) INTO IM_GROUP_MESSAGE_HIST_CNT
        FROM IM_GROUP_MESSAGE_HIST
       WHERE CREATE_DATE >= TRUNC(SYSDATE-30) AND CREATE_DATE < TRUNC(SYSDATE-29) ;
      IF IM_GROUP_MESSAGE_CNT = IM_GROUP_MESSAGE_HIST_CNT 
      THEN
         DELETE FROM IM_GROUP_MESSAGE WHERE CREATE_DATE  >= TRUNC(SYSDATE-30) AND CREATE_DATE < TRUNC(SYSDATE-29) ;
         COMMIT;
         DELETE FROM IM_GROUP_MESSAGE_HIST WHERE CREATE_DATE  < TRUNC(SYSDATE-180) ;
         COMMIT;
         DBMS_OUTPUT.PUT_LINE('0');
         DBMS_OUTPUT.PUT_LINE(ARCH_DATE||' 转档成功：IM_GROUP_MESSAGE ：'||IM_GROUP_MESSAGE_CNT||'，IM_GROUP_MESSAGE_HIST：'||IM_GROUP_MESSAGE_HIST_CNT);

         EXECUTE IMMEDIATE ' ALTER INDEX IDX_IM_GROUP_MESSAGE_01 REBUILD TABLESPACE MPIDX ONLINE ' ;
         EXECUTE IMMEDIATE ' ALTER INDEX IM_GROUP_MESSAGE_PK REBUILD TABLESPACE MPIDX ONLINE ' ;
         EXECUTE IMMEDIATE ' ALTER INDEX IDX_GROUP_MESSAGE_GID REBUILD TABLESPACE MPIDX ONLINE ' ;
         EXECUTE IMMEDIATE ' ALTER INDEX IDX_GROUP_MESSAGE_UID REBUILD TABLESPACE MPIDX ONLINE ' ;
      ELSE
         DBMS_OUTPUT.PUT_LINE('1');
         DBMS_OUTPUT.PUT_LINE(ARCH_DATE||' 转档异常：IM_GROUP_MESSAGE ：'||IM_GROUP_MESSAGE_CNT||'，IM_GROUP_MESSAGE_HIST：'||IM_GROUP_MESSAGE_HIST_CNT);
      END IF;
   ELSE
      DBMS_OUTPUT.PUT_LINE('1');
      DBMS_OUTPUT.PUT_LINE(ARCH_DATE||' 重复转档：IM_GROUP_MESSAGE ：'||IM_GROUP_MESSAGE_CNT||'，IM_GROUP_MESSAGE_HIST：'||IM_GROUP_MESSAGE_HIST_CNT);
   END IF;
   
		   
   END_TIME := DBMS_UTILITY.GET_TIME;
   
   DBMS_OUTPUT.PUT_LINE ('BULK INSERT: '||TO_CHAR(END_TIME-START_TIME) );
   COMMIT;
END;
/


